# Install dependencies
- name: Install required system packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'docker-compose']
  become: true

- name: Install Python Docker packages
  pip:
    name:
    - setuptools
    - docker
    - docker-compose

- name: Add the current user to the docker group
  user:
    name: '{{ ansible_user }}'
    groups: docker
    append: yes
  become: true