# Overrides for production environments

version: "3"

services:
  proxy:
    environment:
      - DOMAIN=${DOMAIN?'DOMAIN environment variable is not defined'}
    ports:
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt

