version: "3"

services:
  db:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - ${MEDIA_FOLDER?'MEDIA_FOLDER environment variable not defined'}/mongo/data/db:/data/db
    command: --quiet
    container_name: db
  
  backend:
    image: codelit/courselit-backend:latest
    environment:
      - API_PREFIX=${API_PREFIX}
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
    volumes:
      - ${MEDIA_FOLDER?'MEDIA_FOLDER environment variable not defined'}:/data
    expose:
      - "8000"
    depends_on:
      - db
    container_name: backend

  frontend:
    image: codelit/courselit-frontend:latest
    environment:
      - SITE_URL=${SITE_URL}
      - API_PREFIX=${API_PREFIX}
      - SSR_SITE_URL=http://backend:8000
    expose:
      - "3000"
    depends_on:
      - backend
    container_name: frontend

  proxy:
    image: codelit/courselit-proxy:latest
    environment:
      - API_PREFIX=${API_PREFIX}
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    container_name: proxy

# volumes:
#   db:
#   uploads:
#     driver: local
#     driver_opts:
#       device: ${MOUNT_UPLOAD_FOLDER_VOLUME_AS}
#       o: bind
#   thumbs:
#     driver: local
#     driver_opts:
#       device: ${MOUNT_THUMBNAIL_FOLDER_VOLUME_AS}
#       o: bind