version: "3"

services:
  proxy:
    environment:
      - DOMAIN=${DOMAIN}
    ports:
      - "443:443"
    volumes:
      - ${MEDIA_FOLDER?'MEDIA_FOLDER environment variable not defined'}/sslcert:/etc/letsencrypt

