- name: Install certbot
  apt: update_cache=yes name=certbot state=present

- name: Run certbot
  command: certbot certonly --standalone --non-interactive --agree-tos -m {{ email }} -d {{ domain }}

- name: Combine certificates
  shell:
      cmd: cat fullchain.pem privkey.pem > haproxy.pem
      chdir: /etc/letsencrypt/live/{{ domain }}/
      creates: haproxy.pem