name: Lint
on: [push]

jobs:
  backend-lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm install
    - name: Backend Lint
      run: npm run lint
      working-directory: ./backend
