name: Build and push images

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERNAME }}
          password: ${{ secrets.DOCKERTOKEN }}

      - name: Build and push backend
        id: docker_build_backend
        uses: docker/build-push-action@v2
        with:
          context: ./services/backend
          file: ./services/backend/Dockerfile
          push: true
          tags: codelit/courselit-backend:latest

      - name: Image digest
        run: echo ${{ steps.docker_build_backend.outputs.digest }}

      - name: Build and push frontend
        id: docker_build_frontend
        uses: docker/build-push-action@v2
        with:
          context: ./services/frontend
          file: ./services/frontend/Dockerfile
          push: true
          tags: codelit/courselit-frontend:latest

      - name: Image digest
        run: echo ${{ steps.docker_build_frontend.outputs.digest }}