name: Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: Configure CI Git User
        run: |
          git config --global user.name 'Rajat Saxena'
          git config --global user.email 'hi@sub.rajatsaxena.dev'
          git remote set-url origin https://$GITHUB_ACTOR:$GITHUB_PAT@github.com/codelitdev/courselit
        env:
          GITHUB_PAT: ${{ secrets.PAT }}

      - name: Checkout and pull branch
        run: git checkout "${GITHUB_REF:11}" && git pull

      - name: Install Packages
        run: yarn install

      - name: Authenticate with Registry
        run: |
          yarn logout
          echo "registry=http://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM }}

      - name: Publish package
        run: yarn lerna publish patch --yes
        env:
          GH_TOKEN: ${{ secrets.PAT }}
          GITHUB_TOKEN: ${{ secrets.PAT }}
          NPM_TOKEN: ${{ secrets.NPM }}

      - name: Setup buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERNAME }}
          password: ${{ secrets.DOCKERTOKEN }}

      - name: Build and push backend
        id: docker_build_backend
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./services/backend/Dockerfile
          push: true
          tags: codelit/courselit-backend:latest

      - name: Image digest
        run: echo ${{ steps.docker_build_backend.outputs.digest }}

      - name: Build and push frontend
        id: docker_build_frontend
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./services/frontend/Dockerfile
          push: true
          tags: codelit/courselit-frontend:latest

      - name: Image digest
        run: echo ${{ steps.docker_build_frontend.outputs.digest }}

      - name: Build and push proxy
        id: docker_build_proxy
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./services/proxy/Dockerfile
          push: true
          tags: codelit/courselit-proxy:latest

      - name: Image digest
        run: echo ${{ steps.docker_build_proxy.outputs.digest }}